version: '3.8'

networks:
  my_network:


services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - fastapi_app
      - fastapi_db
    networks:
      - my_network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources      
    depends_on:
      - prometheus
    networks:
      - my_network
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime_kuma
    ports:
      - "${KUMA_PORT}:${KUMA_PORT}"
    volumes:
      - ./louislam/uptime-kuma-data:/app/data
    restart: unless-stopped
  fastapi_app:
    build: ./fastapi_app
    container_name: fastapi_app
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - fastapi_db
    networks:
      - my_network
  fastapi_db:
    build: ./fastapi_db
    container_name: fastapi_db
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - my_network
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: vincent
      MYSQL_DATABASE: M7-brief1
      MYSQL_USER: vincent
      MYSQL_PASSWORD: vincent
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - my_network
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: vincent
      PMA_PASSWORD: vincent
      MYSQL_ROOT_PASSWORD: vincent
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my_network
volumes:
  db_data:
